pub trait AsciiAlphabeticChar<const C: char> {}
impl AsciiAlphabeticChar<'A'> for char {}
impl AsciiAlphabeticChar<'B'> for char {}
impl AsciiAlphabeticChar<'C'> for char {}
impl AsciiAlphabeticChar<'D'> for char {}
impl AsciiAlphabeticChar<'E'> for char {}
impl AsciiAlphabeticChar<'F'> for char {}
impl AsciiAlphabeticChar<'G'> for char {}
impl AsciiAlphabeticChar<'H'> for char {}
impl AsciiAlphabeticChar<'I'> for char {}
impl AsciiAlphabeticChar<'J'> for char {}
impl AsciiAlphabeticChar<'K'> for char {}
impl AsciiAlphabeticChar<'L'> for char {}
impl AsciiAlphabeticChar<'M'> for char {}
impl AsciiAlphabeticChar<'N'> for char {}
impl AsciiAlphabeticChar<'O'> for char {}
impl AsciiAlphabeticChar<'P'> for char {}
impl AsciiAlphabeticChar<'Q'> for char {}
impl AsciiAlphabeticChar<'R'> for char {}
impl AsciiAlphabeticChar<'S'> for char {}
impl AsciiAlphabeticChar<'T'> for char {}
impl AsciiAlphabeticChar<'U'> for char {}
impl AsciiAlphabeticChar<'V'> for char {}
impl AsciiAlphabeticChar<'W'> for char {}
impl AsciiAlphabeticChar<'X'> for char {}
impl AsciiAlphabeticChar<'Y'> for char {}
impl AsciiAlphabeticChar<'Z'> for char {}
impl AsciiAlphabeticChar<'a'> for char {}
impl AsciiAlphabeticChar<'b'> for char {}
impl AsciiAlphabeticChar<'c'> for char {}
impl AsciiAlphabeticChar<'d'> for char {}
impl AsciiAlphabeticChar<'e'> for char {}
impl AsciiAlphabeticChar<'f'> for char {}
impl AsciiAlphabeticChar<'g'> for char {}
impl AsciiAlphabeticChar<'h'> for char {}
impl AsciiAlphabeticChar<'i'> for char {}
impl AsciiAlphabeticChar<'j'> for char {}
impl AsciiAlphabeticChar<'k'> for char {}
impl AsciiAlphabeticChar<'l'> for char {}
impl AsciiAlphabeticChar<'m'> for char {}
impl AsciiAlphabeticChar<'n'> for char {}
impl AsciiAlphabeticChar<'o'> for char {}
impl AsciiAlphabeticChar<'p'> for char {}
impl AsciiAlphabeticChar<'q'> for char {}
impl AsciiAlphabeticChar<'r'> for char {}
impl AsciiAlphabeticChar<'s'> for char {}
impl AsciiAlphabeticChar<'t'> for char {}
impl AsciiAlphabeticChar<'u'> for char {}
impl AsciiAlphabeticChar<'v'> for char {}
impl AsciiAlphabeticChar<'w'> for char {}
impl AsciiAlphabeticChar<'x'> for char {}
impl AsciiAlphabeticChar<'y'> for char {}
impl AsciiAlphabeticChar<'z'> for char {}

pub trait AsciiAlphabeticCharUpper<const C: char> {}
impl AsciiAlphabeticCharUpper<'A'> for char {}
impl AsciiAlphabeticCharUpper<'B'> for char {}
impl AsciiAlphabeticCharUpper<'C'> for char {}
impl AsciiAlphabeticCharUpper<'D'> for char {}
impl AsciiAlphabeticCharUpper<'E'> for char {}
impl AsciiAlphabeticCharUpper<'F'> for char {}
impl AsciiAlphabeticCharUpper<'G'> for char {}
impl AsciiAlphabeticCharUpper<'H'> for char {}
impl AsciiAlphabeticCharUpper<'I'> for char {}
impl AsciiAlphabeticCharUpper<'J'> for char {}
impl AsciiAlphabeticCharUpper<'K'> for char {}
impl AsciiAlphabeticCharUpper<'L'> for char {}
impl AsciiAlphabeticCharUpper<'M'> for char {}
impl AsciiAlphabeticCharUpper<'N'> for char {}
impl AsciiAlphabeticCharUpper<'O'> for char {}
impl AsciiAlphabeticCharUpper<'P'> for char {}
impl AsciiAlphabeticCharUpper<'Q'> for char {}
impl AsciiAlphabeticCharUpper<'R'> for char {}
impl AsciiAlphabeticCharUpper<'S'> for char {}
impl AsciiAlphabeticCharUpper<'T'> for char {}
impl AsciiAlphabeticCharUpper<'U'> for char {}
impl AsciiAlphabeticCharUpper<'V'> for char {}
impl AsciiAlphabeticCharUpper<'W'> for char {}
impl AsciiAlphabeticCharUpper<'X'> for char {}
impl AsciiAlphabeticCharUpper<'Y'> for char {}
impl AsciiAlphabeticCharUpper<'Z'> for char {}

pub trait AsciiAlphabeticCharLower<const C: char> {}
impl AsciiAlphabeticCharLower<'a'> for char {}
impl AsciiAlphabeticCharLower<'b'> for char {}
impl AsciiAlphabeticCharLower<'c'> for char {}
impl AsciiAlphabeticCharLower<'d'> for char {}
impl AsciiAlphabeticCharLower<'e'> for char {}
impl AsciiAlphabeticCharLower<'f'> for char {}
impl AsciiAlphabeticCharLower<'g'> for char {}
impl AsciiAlphabeticCharLower<'h'> for char {}
impl AsciiAlphabeticCharLower<'i'> for char {}
impl AsciiAlphabeticCharLower<'j'> for char {}
impl AsciiAlphabeticCharLower<'k'> for char {}
impl AsciiAlphabeticCharLower<'l'> for char {}
impl AsciiAlphabeticCharLower<'m'> for char {}
impl AsciiAlphabeticCharLower<'n'> for char {}
impl AsciiAlphabeticCharLower<'o'> for char {}
impl AsciiAlphabeticCharLower<'p'> for char {}
impl AsciiAlphabeticCharLower<'q'> for char {}
impl AsciiAlphabeticCharLower<'r'> for char {}
impl AsciiAlphabeticCharLower<'s'> for char {}
impl AsciiAlphabeticCharLower<'t'> for char {}
impl AsciiAlphabeticCharLower<'u'> for char {}
impl AsciiAlphabeticCharLower<'v'> for char {}
impl AsciiAlphabeticCharLower<'w'> for char {}
impl AsciiAlphabeticCharLower<'x'> for char {}
impl AsciiAlphabeticCharLower<'y'> for char {}
impl AsciiAlphabeticCharLower<'z'> for char {}
